name: Test and lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run RSpec tests and RuboCop lints

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version:
          - 3.2
          - 3.1
          - 3.0
          - 2.7
          - 2.6
          - 2.5

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Ruby v${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rake spec

      - name: Run RuboCop lints
        run: bundle exec rubocop
